const Services = {
  website: [
    {
      id: 1,
      title: "Divinely Developer",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      logo: "/favicon.ico",
      specilize: "Web Developer",
      link: "https://divinelydeveloper.me",
      contact: "+91 7888812282",
      email: "contact@divinelydeveloper.me",
      address: "Rohtak, Haryana",
    },
  ],

  aboutMe: [
    {
      id: 1,
      name: "Bhuneshvar",
      nickName: "Ankit Kalirawana",
      codeName: "imankitkalirawana",
      image: "/imankitkalirawana.jpg",
      tagline: "Crafting digital delights with Web and AI 👋",
      quote:
        "Technology and AI have the power to change our world, but it's up to us to ensure it's for the betterment of humanity.",
      description:
        "Technology and AI have the power to change our world, but it's up to us to ensure it's for the betterment of humanity.",
      specilize: "Web Developer",
      professions: [
        "Developer",
        "Designer",
        "Programmer",
        "Freelancer",
        "Machine Learner",
        "Web Developer",
      ],
      location: "Jhajjar, Haryana",
      email: "imankitkalirawana@gmail.com",
      phone: "+91 7888812282",
    },
  ],
  services: [
    {
      id: 1,
      title: "Web Developement",
      image: "fa-regular fa-window",
      description: "Knowledge of 8+ programming languages",
      color: "#fc9401",
      background: "#fc93014d",
    },
    {
      id: 2,
      title: "UI Design",
      image: "fa-regular fa-sidebar",
      description: "Proficient in creating user-friendly interfaces.",
      color: "#e7385d",
      background: "#e7385e3e",
    },
    {
      id: 3,
      title: "Photo/Video Editing",
      image: "fa-regular fa-camera",
      description: "Proficient in editing visual content.",
      color: "#604868",
      background: "#60486841",
    },
    {
      id: 4,
      title: "App Design",
      image: "fa-regular fa-compass-drafting",
      description: "Knowledge of more than 5 programming languages",
      color: "#fc9401",
      background: "#431922",
    },
  ],
  technologies: [
    {
      id: 1,
      image: "/imankitkalirawana.jpg",
      title: "Web Development",
      techs: [
        {
          id: 1,
          name: "HTML",
        },
        {
          id: 2,
          name: "CSS",
        },
        {
          id: 3,
          name: "JavaScript",
        },
      ],
    },
    {
      id: 2,
      image: "/imankitkalirawana.jpg",
      title: "UX/UI Design",
      techs: [
        {
          id: 1,
          name: "Figma",
        },
        {
          id: 2,
          name: "Adobe XD",
        },
        {
          id: 3,
          name: "Adobe Illustrator",
        },
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Versatile Calculator",
      description:
        "Versatile Calculator is a web app that offers diverse mathematical tools, using HTML, CSS, and JavaScript. It presents a user-friendly interface with multiple calculators for various needs.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/div-calculator",
      previewLink: "https://div-calculator-imankitkalirawana.vercel.app",
      images: [
        "div-calculator-1.png",
        "div-calculator-2.png",
        "div-calculator-3.png",
        "div-calculator-4.png",
      ],
    },
    {
      id: 2,
      title: "Modern Blog Interface",
      description:
        "Our blog combines HTML, CSS, and JavaScript for a sleek and interactive design. HTML structures the content, CSS enhances visuals, and JavaScript adds interactivity, ensuring an engaging and enjoyable reading experience.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/blog",
      previewLink: "https://blog-imankitkalirawana.vercel.app",
      images: ["blog-homepage.png", "blog-page.png"],
    },
    {
      id: 3,
      title: "School Management System",
      description:
        "Our website, built with HTML, CSS, JavaScript, PHP, and SQL, streamlines school operations. HTML and CSS offer a user-friendly interface, while JavaScript adds interactivity. PHP handles dynamic tasks, and SQL databases ensure secure data management.",
      technologies: "HTML, CSS, JS, PHP, SQL",
      link: "https://github.com/imankitkalirawana/school-management-system",
      previewLink: "/error-404",
      images: [
        "school-management-system-1.png",
        "school-management-system-2.png",
        "school-management-system-3.png",
        "school-management-system-4.png",
      ],
    },
    {
      id: 4,
      title: "Links",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/links",
      previewLink: "https://links-imankitkalirawana.vercel.app",
      images: ["links-1.png"],
    },
    {
      id: 5,
      title: "Analog Clock",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/analog-clock",
      previewLink: "https://analog-clock-imankitkalirawana.vercel.app",
      images: ["analog-clock.png"],
    },
    {
      id: 6,
      title: "FOD Livings",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "/error-404",
      previewLink: "/error-404",
      images: ["fod-livings.png"],
    },
    {
      id: 7,
      title: "International Business Game",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/international-business",
      previewLink:
        "https://international-business-imankitkalirawana.vercel.app",
      images: ["international-business.png"],
    },
    {
      id: 8,
      title: "Gagan Institution",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/gagan-institution",
      previewLink: "https://gagan-institution-imankitkalirawana.vercel.app",
      images: ["gagan-institution.png"],
    },
    {
      id: 9,
      title: "Credit Card Mockup",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/credit-card",
      previewLink: "https://credit-card-imankitkalirawana.vercel.app",
      images: ["credit-card.png"],
    },
  ],
  skills: [
    {
      id: 1,
      title: "HTML 5",
      percentage: 90,
      image: "fa-brands fa-html5",
      description:
        "Skilled in HTML, I create structured and accessible web content, ensuring a seamless user experience.",
      color: "#dc4a25",
      background: "#dc4a251e",
      isFontAwesome: true,
    },
    {
      id: 2,
      title: "CSS 3",
      percentage: 90,
      image: "fa-brands fa-css3",
      description:
        "I create visually appealing and responsive web designs through CSS mastery.",
      color: "#2862e9",
      background: "#2862e91f",
      isFontAwesome: true,
    },
    {
      id: 3,
      title: "JS",
      percentage: 80,
      image: "fa-brands fa-js",
      description:
        "I create dynamic and interactive web content using JavaScript.",
      color: "#e8d44d",
      background: "#e8d34d2a",
      isFontAwesome: true,
    },
    {
      id: 4,
      title: "Python",
      percentage: 70,
      image: "fa-brands fa-python",
      description:
        "Proficient in Python basics, I have a strong foundation in programming, enabling me to tackle a wide range of tasks and solve problems efficiently.",
      color: "#4380b0",
      background: "#4381b027",
      isFontAwesome: true,
    },
    {
      id: 5,
      title: "React",
      percentage: 75,
      image: "fa-brands fa-react",
      description:
        "I specialize in React.js, a powerful library for building dynamic and interactive user interfaces. With expertise in component-driven development, I create responsive and engaging web applications that provide a seamless user experience.",
      color: "#5ed4f3",
      background: "#4381b028",
      isFontAwesome: true,
    },
    {
      id: 6,
      title: "Node",
      percentage: 70,
      image: "fa-brands fa-node-js",
      description:
        "I'm in the process of mastering Node.js, a server-side JavaScript runtime, to build scalable and efficient web applications.",
      color: "#509941",
      background: "#50994140",
      isFontAwesome: true,
    },
    {
      id: 7,
      title: "PHP",
      percentage: 70,
      image: "fa-brands fa-php",
      description:
        "Proficient in PHP, I create dynamic web applications and websites with server-side scripting, adding functionality and interactivity to enhance user experiences.",
      color: "#8993be",
      background: "#8993be40",
      isFontAwesome: true,
    },
    {
      id: 8,
      title: "SQL",
      percentage: 70,
      image: "fa-solid fa-database",
      description:
        "I possess a foundational understanding of SQL, allowing me to query databases and manage data effectively, while continuously expanding my skills in database management.",
      color: "#f29111",
      background: "#f291112a",
      isFontAwesome: true,
    },
    {
      id: 9,
      title: "MongoDB",
      percentage: 70,
      image: "fa-brands fa-envira",
      description:
        "Currently exploring MongoDB to gain proficiency in NoSQL database management and enhance my data storage and retrieval skills.",
      color: "#4db33d",
      background: "#4db33d2a",
      isFontAwesome: true,
    },
    {
      id: 10,
      title: "Git",
      percentage: 70,
      image: "fa-brands fa-git-alt",
      description:
        "I am in the early stages of learning Git, a version control system, to manage and collaborate on software development projects.",
      color: "#f05639",
      background: "#f056393d",
      isFontAwesome: true,
    },
    {
      id: 11,
      title: "C++",
      percentage: 70,
      image: "cpp.png",
      description:
        "I am in the early stages of learning C++, a general-purpose programming language, to manage and collaborate on software development projects.",
      color: "#6c7b8b",
      background: "#6c7b8b2a",
      isFontAwesome: false,
    },
    {
      id: 12,
      title: "BootStrap",
      percentage: 70,
      image: "fa-brands fa-bootstrap",
      description:
        "I have a deep understanding of Bootstrap, leveraging its responsive design and UI components to create aesthetically pleasing and user-friendly web interfaces.",
      color: "#563d7c",
      background: "#563d7c2a",
      isFontAwesome: true,
    },
    {
      id: 13,
      title: "Canva",
      percentage: 70,
      image: "canva.png",
      description:
        "I have a deep understanding of Canva, leveraging its responsive design and UI components to create aesthetically pleasing and user-friendly web interfaces.",
      color: "#12a9d2",
      background: "#12a9d22b",
      isFontAwesome: false,
    },
  ],
  education: [
    {
      id: 1,
      title: "Bachelor of computer science and technology",
      institutionShort: "LPU",
      institutionLong: "Lovely Professional University",
      location: "Phagwara, Punjab",
      year: "2026",
      link: "https://www.lpu.in",
    },
    {
      id: 2,
      title: "XIIth from CBSE",
      institutionShort: "ASSS",
      institutionLong: "Adarsh Sr. Sec. School",
      location: "Jhajjar, Haryana",
      year: "2021",
      link: "https://schools.org.in/jhajjar/06150401002/adarsh-sr-sec-school-dadanpur.html",
    },
    {
      id: 3,
      title: "Xth from CBSE",
      institutionShort: "ASSS",
      institutionLong: "Adarsh Sr. Sec. School",
      location: "Jhajjar, Haryana",
      year: "2019",
      link: "https://schools.org.in/jhajjar/06150401002/adarsh-sr-sec-school-dadanpur.html",
    },
  ],
  certificates: [
    {
      id: 1,
      priority: 3,
      title: "Introduction to HTML, CSS and Javascript",
      image: "1.png",
      institution: "IBM",
      location: "Online",
      year: "2022",
      duration: "12hrs",
      link: "https://coursera.org/share/d62c0e3891b61b3bb5bea3981df8fc81",
    },
    {
      id: 2,
      priority: 3,
      title: "Introduction to Cloud Computing",
      image: "2.png",
      institution: "IBM",
      location: "Online",
      year: "2022",
      duration: "12hrs",
      link: "https://coursera.org/share/4f9640a4e6eecadbb755c8485a3c76e4",
    },
    {
      id: 3,
      priority: 2,
      title: "Getting Started with AI and Machine Learning",
      image: "3.png",
      institution: "LinkedIn",
      location: "Online",
      year: "2023",
      duration: "9hrs",
      link: "https://www.linkedin.com/learning/certificates/8aa845d977a5904fe0903b4c4848c68bc78927251ed5e90df2dc1094c30c6fa6",
    },
    {
      id: 4,
      priority: 3,
      title: "Computer Architecture and Organization",
      image: "4.png",
      institution: "Udemy",
      location: "Online",
      year: "2023",
      duration: "12hrs",
      link: "https://www.udemy.com/certificate/UC-fb8a6728-5817-493b-a993-adede0a5fdd6/",
    },
    {
      id: 5,
      priority: 3,
      title: "Fundamentals of Management",
      image: "5.png",
      institution: "UCI",
      location: "Online",
      year: "2023",
      duration: "6hrs",
      link: "https://coursera.org/share/d175e0b3fce0742c82cb385b724dc7df",
    },
  ],
  links: [
    {
      id: 1,
      title: "X",
      link: "https://twitter.com/divinelydevs",
      icon: "fa-brands fa-twitter",
      color: "#22a0f0",
      featured: 1,
    },
    {
      id: 2,
      title: "LinkedIn",
      link: "https://linkedin.com/in/bhuneshvar",
      icon: "fa-brands fa-linkedin",
      color: "#0077b5",
      featured: 1,
    },
    {
      id: 3,
      title: "Telegram",
      link: "https://telegram.me/divinelydevelopers",
      icon: "fa-brands fa-telegram-plane",
      color: "#0088cc",
      featured: 0,
    },
    {
      id: 4,
      title: "Instagram",
      link: "https://instagram.com/divinelydeveloper",
      icon: "fa-brands fa-instagram",
      color: "#e1306c",
      featured: 1,
    },
    {
      id: 5,
      title: "Github",
      link: "https://github.com/imankitkalirawana",
      icon: "fa-brands fa-github",
      color: "#333333",
      featured: 1,
    },
    {
      id: 6,
      title: "Upwork",
      link: "https://www.upwork.com/freelancers/~0147f7ac104ec5582d?viewMode=1",
      icon: "fa-regular fa-diagram-project",
      color: "#6fda44",
      featured: 0,
    },
    {
      id: 7,
      title: "Discord",
      link: "https://discord.gg/J3XKCw8pAh",
      icon: "fa-brands fa-discord",
      color: "#7289da",
      featured: 0,
    },
    {
      id: 8,
      title: "Stack Overflow",
      link: "https://stackoverflow.com/users/18383073/bhuneshvar",
      icon: "fa-brands fa-stack-overflow",
      color: "#f48024",
      featured: 0,
    },
    {
      id: 9,
      title: "Twitch",
      link: "https://www.twitch.tv/imankitkalirawana",
      icon: "fa-brands fa-twitch",
      color: "#6441a5",
      featured: 0,
    },
    {
      id: 10,
      title: "Reddit",
      link: "https://www.reddit.com/r/imankitkalirawana",
      icon: "fa-brands fa-reddit",
      color: "#ff4500",
      featured: 0,
    },
    {
      id: 11,
      title: "Paypal",
      link: "https://www.paypal.com/paypalme/ankitkalirawana?country.x=IN&locale.x=en_GB",
      icon: "fa-brands fa-paypal",
      color: "#0079c1",
      featured: 0,
    },
    {
      id: 12,
      title: "Slack",
      link: "https://imankitkalirawana.slack.com/",
      icon: "fa-brands fa-slack",
      color: "#4a154b",
      featured: 0,
    },
    {
      id: 13,
      title: "Quora",
      link: "https://www.quora.com/profile/Ankit-Kalirawana-2",
      icon: "fa-brands fa-quora",
      color: "#a82400",
      featured: 0,
    },
    {
      id: 14,
      title: "Bitbucket",
      link: "https://bitbucket.org/imankitkalirawana/",
      icon: "fa-brands fa-bitbucket",
      color: "#0052cc",
      featured: 0,
    },
    {
      id: 15,
      title: "Gitlab",
      link: "https://gitlab.com/imankitkalirawana",
      icon: "fa-brands fa-gitlab",
      color: "#fc6d26",
      featured: 0,
    },
    {
      id: 16,
      title: "Google Developers",
      link: "https://developers.google.com/profile/u/imankitkalirawana",
      icon: "fa-brands fa-google",
      color: "#4285f4",
      featured: 0,
    },
    {
      id: 17,
      title: "Dribbble",
      link: "https://dribbble.com/imankitkalirawana",
      icon: "fa-brands fa-dribbble",
      color: "#ea4c89",
      featured: 0,
    },
    {
      id: 18,
      title: "Codepen",
      link: "https://codepen.io/imankitkalirawana",
      icon: "fa-brands fa-codepen",
      color: "#000000",
      featured: 0,
    },
    {
      id: 19,
      title: "Medium",
      link: "https://imankitkalirawana.medium.com/",
      icon: "fa-brands fa-medium",
      color: "#000000",
      featured: 0,
    },
    {
      id: 20,
      title: "Behance",
      link: "https://www.behance.net/ankitkalirawana1",
      icon: "fa-brands fa-behance",
      color: "#1769ff",
      featured: 0,
    },
    {
      id: 21,
      title: "Pinterest",
      link: "https://in.pinterest.com/imankitkalirawana/",
      icon: "fa-brands fa-pinterest",
      color: "#e60023",
      featured: 0,
    },
    {
      id: 22,
      title: "Showwcase",
      link: "https://showwcase.com/imankitkalirawana",
      icon: "fa-regular fa-backpack",
      color: "#000000",
      featured: 0,
    },
    {
      id: 23,
      title: "HackerRank",
      link: "https://www.hackerrank.com/ankitkalirawana",
      icon: "fa-brands fa-hackerrank",
      color: "#2ec866",
      featured: 0,
    },
    {
      id: 24,
      title: "Deviant Art",
      link: "https://www.deviantart.com/imankitkalirawana",
      icon: "fa-brands fa-deviantart",
      color: "#05cc47",
      featured: 0,
    },
  ],
};

export default Services;
