const Services = {
  website: [
    {
      id: 1,
      title: "Divinely Developer",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      logo: "/favicon.ico",
      specilize: "Web Developer",
      link: "https://divinelydeveloper.me",
      contact: "+91 7888812282",
      email: "contact@divinelydeveloper.me",
      address: "Rohtak, Haryana",
    },
  ],

  aboutMe: [
    {
      id: 1,
      name: "Bhuneshvar",
      nickName: "Ankit Kalirawana",
      codeName: "imankitkalirawana",
      image: "/imankitkalirawana.jpg",
      tagline: "Crafting digital delights with Web and AI 👋",
      quote:
        "Technology and AI have the power to change our world, but it's up to us to ensure it's for the betterment of humanity.",
      description:
        "Technology and AI have the power to change our world, but it's up to us to ensure it's for the betterment of humanity.",
      specilize: "Web Developer",
      professions: [
        "Developer",
        "Designer",
        "Programmer",
        "Freelancer",
        "Machine Learner",
        "Web Developer",
      ],
      location: "Jhajjar, Haryana",
      email: "imankitkalirawana@gmail.com",
      phone: "+91 7888812282",
    },
  ],
  services: [
    {
      id: 1,
      title: "Web Developement",
      image: "fa-regular fa-window",
      description: "Knowledge of more than 5 programming languages",
      color: "#fc9401",
      background: "#fc93014d",
    },
    {
      id: 2,
      title: "UI Design",
      image: "fa-regular fa-sidebar",
      description: "Knowledge of more than 5 programming languages",
      color: "#e7385d",
      background: "#e7385e3e",
    },
    {
      id: 3,
      title: "Photo/Video Editing",
      image: "fa-regular fa-camera",
      description: "Knowledge of more than 5 programming languages",
      color: "#604868",
      background: "#60486841",
    },
    {
      id: 4,
      title: "App Design",
      image: "fa-regular fa-compass-drafting",
      description: "Knowledge of more than 5 programming languages",
      color: "#fc9401",
      background: "#431922",
    },
  ],
  technologies: [
    {
      id: 1,
      image: "/imankitkalirawana.jpg",
      title: "Web Development",
      techs: [
        {
          id: 1,
          name: "HTML",
        },
        {
          id: 2,
          name: "CSS",
        },
        {
          id: 3,
          name: "JavaScript",
        },
      ],
    },
    {
      id: 2,
      image: "/imankitkalirawana.jpg",
      title: "UX/UI Design",
      techs: [
        {
          id: 1,
          name: "Figma",
        },
        {
          id: 2,
          name: "Adobe XD",
        },
        {
          id: 3,
          name: "Adobe Illustrator",
        },
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Div Calculator",
      description:
        "Versatile Calculator Collection is a web app that offers diverse mathematical tools, using HTML, CSS, and JavaScript. It presents a user-friendly interface with multiple calculators for various needs.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/div-calculator",
      previewLink: "https://div-calculator-imankitkalirawana.vercel.app",
      images: [
        "div-calculator-1.png",
        "div-calculator-2.png",
        "div-calculator-3.png",
        "div-calculator-4.png",
      ],
    },
    {
      id: 2,
      title: "Blog Website",
      // images: "blog-homepage-1.png",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/blog",
      previewLink: "https://blog-imankitkalirawana.vercel.app",
      images: ["blog-homepage.png", "blog-page.png"],
    },
    {
      id: 3,
      title: "School Management System",
      // images: "school-management-system-1.png",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS, PHP, SQL",
      link: "https://github.com/imankitkalirawana/school-management-system",
      previewLink: "/error-404",
      images: [
        "school-management-system-1.png",
        "school-management-system-2.png",
        "school-management-system-3.png",
        "school-management-system-4.png",
      ],
    },
    {
      id: 4,
      title: "Links",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/links",
      previewLink: "https://links-imankitkalirawana.vercel.app",
      images: ["links-1.png"],
    },
    {
      id: 5,
      title: "Analog Clock",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/analog-clock",
      previewLink: "https://analog-clock-imankitkalirawana.vercel.app",
      images: ["analog-clock.png"],
    },
    {
      id: 6,
      title: "FOD Livings",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "/error-404",
      previewLink: "/error-404",
      images: ["fod-livings.png"],
    },
    {
      id: 7,
      title: "International Business Game",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/international-business",
      previewLink:
        "https://international-business-imankitkalirawana.vercel.app",
      images: ["international-business.png"],
    },
    {
      id: 8,
      title: "Gagan Institution",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/gagan-institution",
      previewLink: "https://gagan-institution-imankitkalirawana.vercel.app",
      images: ["gagan-institution.png"],
    },
    {
      id: 9,
      title: "Credit Card Mockup",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/imankitkalirawana/credit-card",
      previewLink: "https://credit-card-imankitkalirawana.vercel.app",
      images: ["credit-card.png"],
    },
  ],
  skills: [
    {
      id: 1,
      title: "HTML 5",
      percentage: 90,
      image: "fa-brands fa-html5",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#dc4a25",
      background: "#dc4a251e",
      isFontAwesome: true,
    },
    {
      id: 2,
      title: "CSS 3",
      percentage: 90,
      image: "fa-brands fa-css3",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#2862e9",
      background: "#2862e91f",
      isFontAwesome: true,
    },
    {
      id: 3,
      title: "JS",
      percentage: 80,
      image: "fa-brands fa-js",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#e8d44d",
      background: "#e8d34d2a",
      isFontAwesome: true,
    },
    {
      id: 4,
      title: "Python",
      percentage: 70,
      image: "fa-brands fa-python",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#4380b0",
      background: "#4381b027",
      isFontAwesome: true,
    },
    {
      id: 5,
      title: "React",
      percentage: 75,
      image: "fa-brands fa-react",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#5ed4f3",
      background: "#4381b028",
      isFontAwesome: true,
    },
    {
      id: 6,
      title: "Node",
      percentage: 70,
      image: "fa-brands fa-node-js",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#509941",
      background: "#50994140",
      isFontAwesome: true,
    },
    {
      id: 7,
      title: "PHP",
      percentage: 70,
      image: "fa-brands fa-php",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#8993be",
      background: "#8993be40",
      isFontAwesome: true,
    },
    {
      id: 8,
      title: "SQL",
      percentage: 70,
      image: "fa-solid fa-database",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#f29111",
      background: "#f291112a",
      isFontAwesome: true,
    },
    {
      id: 9,
      title: "MongoDB",
      percentage: 70,
      image: "fa-brands fa-envira",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#4db33d",
      background: "#4db33d2a",
      isFontAwesome: true,
    },
    {
      id: 10,
      title: "Git",
      percentage: 70,
      image: "fa-brands fa-git-alt",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#f05639",
      background: "#f056393d",
      isFontAwesome: true,
    },
    {
      id: 11,
      title: "C++",
      percentage: 70,
      image: "cpp.png",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#6c7b8b",
      background: "#6c7b8b2a",
      isFontAwesome: false,
    },
    {
      id: 12,
      title: "BootStrap",
      percentage: 70,
      image: "fa-brands fa-bootstrap",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#563d7c",
      background: "#563d7c2a",
      isFontAwesome: true,
    },
    {
      id: 13,
      title: "Canva",
      percentage: 70,
      image: "canva.png",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      color: "#12a9d2",
      background: "#12a9d22b",
      isFontAwesome: false,
    },
  ],
  education: [
    {
      id: 1,
      title: "Bachelor of computer science and technology",
      institutionShort: "LPU",
      institutionLong: "Lovely Professional University",
      location: "Phagwara, Punjab",
      year: "2026",
      link: "https://divinelydeveloper.me",
    },
    {
      id: 2,
      title: "XIIth from CBSE",
      institutionShort: "ASSS",
      institutionLong: "Adarsh Sr. Sec. School",
      location: "Jhajjar, Haryana",
      year: "2021",
      link: "https://divinelydeveloper.me",
    },
    {
      id: 3,
      title: "Xth from CBSE",
      institutionShort: "ASSS",
      institutionLong: "Adarsh Sr. Sec. School",
      location: "Jhajjar, Haryana",
      year: "2019",
      link: "https://divinelydeveloper.me",
    },
  ],
  certificates: [
    {
      id: 1,
      priority: 4,
      title: "Introduction to HTML, CSS and Javascript",
      image: "1.png",
      institution: "IBM",
      location: "Online",
      year: "2022",
      duration: "12hrs",
      link: "https://coursera.org/share/d62c0e3891b61b3bb5bea3981df8fc81",
    },
    {
      id: 2,
      priority: 3,
      title: "Introduction to Cloud Computing",
      image: "2.png",
      institution: "IBM",
      location: "Online",
      year: "2022",
      duration: "12hrs",
      link: "https://coursera.org/share/4f9640a4e6eecadbb755c8485a3c76e4",
    },
    {
      id: 3,
      priority: 2,
      title: "Getting Started with AI and Machine Learning",
      image: "3.png",
      institution: "LinkedIn",
      location: "Online",
      year: "2023",
      duration: "9hrs",
      link: "https://www.linkedin.com/learning/certificates/8aa845d977a5904fe0903b4c4848c68bc78927251ed5e90df2dc1094c30c6fa6",
    },
  ],
  links: [
    {
      id: 1,
      title: "X",
      link: "https://twitter.com/divinelydevs",
      icon: "fa-brands fa-twitter",
      // <i class="fa-brands fa-x-twitter"></i>
      color: "#22a0f0",
    },
    {
      id: 2,
      title: "LinkedIn",
      link: "https://linkedin.com/in/bhuneshvar",
      icon: "fa-brands fa-linkedin",
      color: "#0077b5",
    },
    {
      id: 3,
      title: "Telegram",
      link: "https://telegram.me/divinelydevelopers",
      icon: "fa-brands fa-telegram-plane",
      color: "#0088cc",
    },
    {
      id: 4,
      title: "Instagram",
      link: "https://instagram.com/divinelydevs",
      icon: "fa-brands fa-instagram",
      color: "#e1306c",
    },
    {
      id: 5,
      title: "Github",
      link: "https://github.com/imankitkalirawana",
      icon: "fa-brands fa-github",
      color: "#333333",
    },
  ],
};

export default Services;
